"""Add avatar column to Users table

Revision ID: 3be451bb6204
Revises: 552fc42522ec
Create Date: 2024-06-05 23:04:06.609531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3be451bb6204'
down_revision = '552fc42522ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Albums', schema=None) as batch_op:
        batch_op.alter_column('AlbumName',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('Artist',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('Cards', schema=None) as batch_op:
        batch_op.alter_column('AlbumID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('Word',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('Translate',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('Line',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('TranslateLine',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)

    with op.batch_alter_table('Roles', schema=None) as batch_op:
        batch_op.alter_column('RoleName',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('UserCards', schema=None) as batch_op:
        batch_op.alter_column('UserID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('CardID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=100), nullable=True))
        batch_op.alter_column('FirstName',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('LastName',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('Email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('Password',
               existing_type=mysql.VARCHAR(length=400),
               nullable=False)
        batch_op.alter_column('RoleID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('RoleID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('Password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('Email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('LastName',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('FirstName',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('avatar')

    with op.batch_alter_table('UserCards', schema=None) as batch_op:
        batch_op.alter_column('CardID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('UserID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('Roles', schema=None) as batch_op:
        batch_op.alter_column('RoleName',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('Cards', schema=None) as batch_op:
        batch_op.alter_column('TranslateLine',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('Line',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('Translate',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('Word',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('AlbumID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('Albums', schema=None) as batch_op:
        batch_op.alter_column('Artist',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('AlbumName',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
