"""update_model_User

Revision ID: 4373a482b32f
Revises: 3be451bb6204
Create Date: 2024-06-05 23:51:18.259875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4373a482b32f'
down_revision = '3be451bb6204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserCards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('Password',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=400),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.alter_column('Password',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('UserCards', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
